donor/urls.py
from django.urls import path
from . import views

app_name = 'donor'
urlpatterns = [
	path('', views.add_info, name='index'),
	path('add-info/', views.add_info, name='add-info'),
	path('search/', views.search, name='search'),
]

landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'
urlpatterns = [
	path('', views.index),
	path('home/', views.home, name='home'),
]

lifestream/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('landing.urls')),
    path('admin/', admin.site.urls),
    path('donor/', include('donor.urls')),
    path('search/', include('search.urls')),

]

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
	path('', views.index, name='index')
]

donor/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator

class Donor(models.Model):
	A_POS  = 'A+'
	A_NEG  = 'A-'
	B_POS  = 'B+'
	B_NEG  = 'B-'
	AB_POS = 'AB+'
	AB_NEG = 'AB-'
	O_POS  = 'O+'
	O_NEG  = 'O-'
	BLOOD_GROUP_CHOICES = [
		(A_POS, 'A+ (positive)'),
		(A_NEG, 'A- (negative)'),
		(B_POS, 'B+ (positive)'),
		(B_NEG, 'B- (negative)'),
		(AB_POS, 'AB+ (positive)'),
		(AB_POS, 'AB- (negative)'),
		(O_POS, 'O+ (positive)'),
		(O_POS, 'O- (negative)'),
	]


	# name
	name = models.CharField(
		max_length=30,
		default=''
		)

	# blood group choices
	blood_group = models.CharField(
		max_length=3,
		choices = BLOOD_GROUP_CHOICES,
		default=A_POS,
	)

	# gender
	gender = models.CharField(
		max_length=1,
		choices = [('m', 'Male'), ('f', 'Female')]
	)

	# age
	age = models.IntegerField(validators=[MinValueValidator(17), MaxValueValidator(70)])

	# location
	location = models.CharField(max_length=100, default='')

	# phone
	phone_regex = RegexValidator(regex=r'^[0]{1}[\d]{10}',
		message="Phone number must be of the form: 01XXXXXXXXX")
	phone_number = models.CharField(validators=[phone_regex], max_length=11, default='')

landing/models.py
from django.db import models

# Create your models here.

search/models.py
from django.db import models

# Create your models here.

donor/forms.py
from django import forms
from django.forms import ModelForm
from .models import Donor

class DonorForm(ModelForm):
    required_css_class = 'required'
    class Meta:
    	# the model this form should be based on
        model = Donor
        # form should include all fields
        fields = '__all__'

donor/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from .forms import DonorForm
from .models import Donor

def index(request):
	context = {'req': request.GET}

	return render(request, 'donor/index.html', context)


def add_info(request):
	submitted = False
	if request.method == 'POST':
		form = DonorForm(request.POST)
		if form.is_valid():
			form.save()
			response = redirect('add-info/?submitted=True')
			return response
	else:
		form = DonorForm()
		if 'submitted' in request.GET:
			submitted = True
	context = {'form': form,
				'submitted': submitted
			}
	return render(request, 'donor/add_info_form.html', context)


def search(request):
	data = Donor.objects.all()

	d = [p for p in request.GET.values()]
	if len(d) != 0:
		# starting of query string
		query = 'data.filter('
		for p in request.GET:
			if p == 'blood_group' and request.GET.get(p) != '':

				# use case insensitive regex to search blood_group
				# beginning with param
				query += f"{p}__iregex=r'^{request.GET.get(p)}',"

				# to avoid running the next if block
				continue

			if request.GET.get(p) != '':
				query += f'{p}__icontains="{request.GET.get(p)}",'

		if query[:] == ',':
			query = f'{query[:-1]}'
		query = f'{query})'

		# get the return value of executing the string
		data = eval(query)

	context = {'data': data,
				'request': request.GET
			}
	return render(request, 'donor/search.html', context)

landing/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect

def index(request):
	response = redirect('home/')
	return response


def home(request):
	myobj = {
				'hello': 'hello world',
				'req'  : request.GET
			}
	return render(request, 'landing/home.html', myobj)

search/views.py
from django.http import HttpResponse
from django.shortcuts import render
# from django.shortcuts import redirect


def index(request):
	return render(request, 'search/index.html')

donor/templates/donor/add_info_form.html
<!-- # donor/add_info_form.html -->

{% extends "lifestream/base.html" %}

{% block title %}LifeStream | Become A Donor{% endblock title %}

{% block content %}

{% if submitted %}
	<div class="ui middle aligned center aligned grid u-no-top-margin u-relative">
    	<div class='ui success message div-center'>
	        <p>Your information has been saved. Thank you.</p>
        </div>
	    <a href="{% url 'landing:home' %}" class="a--back">Go home</a>
	</div>

{% else %}

	<div class="register-form">
		<div class="ui middle aligned center aligned grid u-no-top-margin">
			<form action='' method='POST' novalidate="">
		    <!-- {{ form.non_field_errors }} -->
		    {% csrf_token %}

			{% if form.non_field_errors %}
			    <ul>
			      {% for error in form.non_field_errors %}
			        <li>{{ error }}</li>
			      {% endfor %}
			    </ul>
			  {% endif %}

			{% for hidden_field in form.hidden_fields %}
				{% if hidden_field.errors %}
					<ul>
					{% for error in hidden_field.errors %}
						<li>(Hidden field {{ hidden_field.name }}) {{ error }}</li>
					{% endfor %}
					</ul>
				{% endif %}
				{{ hidden_field }}
			{% endfor %}

			<div class="u-center">
				<h1>Register yourself as a Donor</h1>
			</div>

			<div class="ui form">
			    {% for field in form.visible_fields %}
				<div class="field">
					{% if field.errors %}
			            {% for error in field.errors %}
							<div class="ui negative message">
								<p>{{ error }}</p>
							</div>
						{% endfor %}
					{% endif %}
					{{ field.label_tag }}
					{{ field }}
				</div>
				{% endfor %}
				<input type="submit" class='btn' value="submit">
			</div>
			<a href="{% url 'landing:home' %}" class="a--back">Go home</a>
			</form>
		</div>
	</div>

{% endif %}
{% endblock content %}

donor/templates/donor/index.html
<!-- donor/index.html -->

{% extends 'lifestream/base.html' %}

{% block title %}
Lifestream | Donor
{% endblock title %}


{% block content %}
{% if not req %}
	<p>req not defined!!</p>
	<a href="{{request.META.HTTP_REFERER}}">Go back</a>
{% endif %}
{% endblock content %}

donor/templates/donor/search.html
<!-- /donor/search.html -->

{% extends 'lifestream/base.html' %}

{% block title %}
LifeStream | Search
{% endblock title %}

{% block content %}

	<div class='container--search'>
		<div class="ui form">
			<form action='' method='GET' novalidate="" class='search--form'>
				<div class="fields">
					<div class="field">
						<label>Blood Group</label>
						<input type="text" name="blood_group" placeholder="e.g. A+, b+, o-" value="{{ request.blood_group }}">
					</div>
					<div class="field">
						<label>Age</label>
						<input type="number" name="age" placeholder="e.g. 34, 53" value="{{ request.age }}">
					</div>
					<div class="field">
						<label>Gender</label>
						<input type="text" name="gender" placeholder="m or f" value="{{ request.gender }}">
					</div>
					<div class="field">
						<label>Location</label>
						<input type="text" name="location" placeholder="e.g. dhaka" value="{{ request.location }}">
					</div>
				</div>
				<input type="submit" class='btn' value="filter">
				<a class='btn u-margin-left-medium' href="{% url 'donor:search' %}">clear filter</a>
			</form>
		</div>


		<div class='data-table'>
			<div class='ui middle aligned center aligned grid u-no-top-margin'>
				<table class="ui celled table">
				  <thead>
				    <tr><th>Name</th>
				    <th>Blood Group</th>
				    <th>Age</th>
				    <th>Gender</th>
				    <th>Location</th>
				    <th>Phone</th>
				  </tr></thead>
				  <tbody>
				  	{% for item in data %}
				    <tr>
				      <td data-label="Name">{{ item.name }}</td>
				      <td data-label="Blood Group">{{ item.blood_group }}</td>
				      <td data-label="Age">{{ item.age }}</td>
				      <td data-label="Gender">{{ item.gender }}</td>
				      <td data-label="Location">{{ item.location }}</td>
				      <td data-label="Phone">{{ item.phone_number }}</td>
				    </tr>
				    {% endfor %}
				  </tbody>
				</table>
			</div>
			<a href="{% url 'landing:home' %}" class='a--back'>Go home</a>
		</div>
	</div>
{% endblock content %}

landing/templates/landing/home.html
<!-- /landing/home.html -->

{% extends 'lifestream/base.html' %}

{% block title %}
LifeStream | Home
{% endblock title %}

{% block content %}
<section class='section-landing'>

<div class='container container--landing'>
	<div class='quote u-margin-bottom'>
		<p class='quote--main'>“The purpose of human life is to serve, and to show compassion and the will to help others.”  – Albert Schweitzer</p>
	</div>
	<div class='container'>

		<a href='{% url "donor:index" %}' class='btn u-gutter-horizontal'>Become A Donor</a>
		<div class='divider divider--small'></div>
		<a href='{% url "donor:search" %}' class='btn'>Find A Donor</a>
	</div>
</div>

</section>
{% endblock content %}

search/templates/search/index.html
<!-- search/index.html -->

{% extends 'lifestream/base.html'%}

{% block title %}
Lifestream | Search
{% endblock title %}


{% block content %}
<p>just sitting here</p>
<a href="{{request.META.HTTP_REFERER}}">Go back</a>
{% endblock content %}

templates/lifestream/base.html
<!-- lifestream/base.html  -->

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	{% load static %}
	<!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/form.min.css"> -->
	<!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/table.min.css"> -->
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
	<link href="https://fonts.googleapis.com/css?family=Roboto:100,500,900&display=swap" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'lifestream/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'landing/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'donor/style.css' %}">

	<title>
		{% block title %}
			LifeStream
		{% endblock title %}
	</title>
</head>
<body>

{% block content %}

{% endblock content %}

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>
</body>
</html>